#!/bin/sh

LFS=${LFS:-/mnt/lfs}

if [ `whoami` != "lfs" ]
  then echo "Please run as lfs"
  exit
fi

cat > ~/.bash_profile << "EOF"
exec env -i HOME=$HOME TERM=$TERM PS1='\u:\w\$ ' /bin/bash
EOF

cat > ~/.bashrc << "EOF"
set +h
umask 022
LFS=/mnt/lfs
LC_ALL=POSIX
LFS_TGT=$(uname -m)-lfs-linux-gnu
PATH=/tools/bin:/bin:/usr/bin
MAKEFLAGS='-j 5'
export LFS LC_ALL LFS_TGT PATH MAKEFLAGS
EOF

source ~/.bash_profile

