#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

strip --strip-debug /tools/lib/*
/usr/bin/strip --strip-unneeded /tools/{,s}bin/*

rm -rf /tools/{,share}/{info,man,doc}

find /tools/{lib,libexec} -name \*.la -delete

chown -R root:root $LFS/tools

