#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

mkdir -pv $LFS/{dev,proc,sys,run}
mknod -m 600 $LFS/dev/console c 5 1
mknod -m 666 $LFS/dev/null c 1 3
mount -v --bind /dev $LFS/dev
mount -vt devpts devpts $LFS/dev/pts -o gid=5,mode=620
mount -vt proc proc $LFS/proc
mount -vt sysfs sysfs $LFS/sys
mount -vt tmpfs tmpfs $LFS/run

if [ -h $LFS/dev/shm ]; then
	mkdir -pv $LFS/$(readlink $LFS/dev/shm)
fi

pushd $LFS/tools
wget -qc --show-progress http://www.linuxfromscratch.org/hints/downloads/files/ATTACHMENTS/more_control_and_pkg_man/more_control_helpers.tar.bz2
tar xjf more_control_helpers.tar.bz2
cd more_control_helpers
cp ./sbin/* /tools/bin
popd

cp 11-prepare-lfs-system-2 $LFS
cp -r pkg $LFS/usr/pkg

