#!/tools/bin/bash

set -o errexit
set -o pipefail
set -o nounset

###############################################################################
# 6.5 Creating Directories
###############################################################################

mkdir -pv /{bin,boot,etc/{opt,sysconfig},home,lib/firmware,mnt,opt}
mkdir -pv /{media/{floppy,cdrom},sbin,srv,var}
install -dv -m 0750 /root
install -dv -m 1777 /tmp /var/tmp
mkdir -pv /usr/{,local/}{bin,include,lib,sbin,src}
mkdir -pv /usr/{,local/}share/{color,dict,doc,info,locale,man}
mkdir -pv  /usr/{,local/}share/{misc,terminfo,zoneinfo}
mkdir -pv  /usr/libexec
mkdir -pv /usr/{,local/}share/man/man{1..8}

case $(uname -m) in
	x86_64) mkdir -pv /lib64 ;;
esac

mkdir -pv /var/{log,mail,spool}
ln -svf /run /var/run
ln -svf /run/lock /var/lock
mkdir -pv /var/{opt,cache,lib/{color,misc,locate},local}

###############################################################################
# 6.6. Creating Essential Files and Symlinks 
###############################################################################

ln -svf /tools/bin/{bash,cat,chmod,dd,echo,ln,mkdir,pwd,rm,stty,touch} /bin
ln -svf /tools/bin/{env,install,perl,printf}         /usr/bin
ln -svf /tools/lib/libgcc_s.so{,.1}                  /usr/lib
ln -svf /tools/lib/libstdc++.{a,so{,.6}}             /usr/lib

install -vdm755 /usr/lib/pkgconfig

ln -svf bash /bin/sh

ln -svf /proc/self/mounts /etc/mtab

cat > /etc/passwd << "EOF"
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/dev/null:/bin/false
daemon:x:6:6:Daemon User:/dev/null:/bin/false
messagebus:x:18:18:D-Bus Message Daemon User:/var/run/dbus:/bin/false
nobody:x:99:99:Unprivileged User:/dev/null:/bin/false
EOF

cat > /etc/group << "EOF"
root:x:0:
bin:x:1:daemon
sys:x:2:
kmem:x:3:
tape:x:4:
tty:x:5:
daemon:x:6:
floppy:x:7:
disk:x:8:
lp:x:9:
dialout:x:10:
audio:x:11:
video:x:12:
utmp:x:13:
usb:x:14:
cdrom:x:15:
adm:x:16:
messagebus:x:18:
input:x:24:
mail:x:34:
kvm:x:61:
wheel:x:97:
nogroup:x:99:
users:x:999:
EOF

touch /var/log/{btmp,lastlog,faillog,wtmp}
chgrp -v utmp /var/log/lastlog
chmod -v 664  /var/log/lastlog
chmod -v 600  /var/log/btmp

###############################################################################
# User based package management
###############################################################################

cp -a /tools/more_control_helpers/etc /etc/pkgusr
chown -R 0:0 /etc/pkgusr
cp -a /tools/more_control_helpers/lib /usr/lib/pkgusr
chown -R 0:0 /usr/lib/pkgusr
cp /tools/more_control_helpers/bin/* /usr/bin
cp /tools/more_control_helpers/sbin/* /usr/sbin
rm /usr/sbin/{useradd,groupadd}

#groupadd -g 9999 install

for d in $(cat /tools/more_control_helpers/installdirs.lst); do
	[ -d $d ] || mkdir -vp $d
done

chown 0:9999 $(cat /tools/more_control_helpers/installdirs.lst)
chmod ug=rwx,o=rxt $(cat /tools/more_control_helpers/installdirs.lst)

